language: csharp
env:
  global:
  - ARTIFACTS_S3_BUCKET=erdos
  - ARTIFACTS_AWS_REGION=eu-west-1
  - ARTIFACTS_AWS_ACCESS_KEY_ID=AKIAIJ6RNS2NO5AJFEWA
  - secure: "Fcch2TfSEG5YqT42JwExtS608pc395gdx4mMj++leKzVyA7vMRqoO2PLM38AGtTCTNiegIw97BPzwamDWO16WCzCYCOBQcCUKZ5N5raXhMEFr8Q4+zOniGuK/Q1G78rwC6VEafdoN/4/SFGhKl/e/WL079dwZ1oyIKeHT7ih9lE="
solution: src/Plankton.sln
after_success:
- zip plankton-${TRAVIS_BUILD_NUMBER}.zip LICENSE.txt README.md
- zip -j plankton-${TRAVIS_BUILD_NUMBER}.zip bin/Release/Plankton.dll bin/Release/Plankton.gha
- travis-artifacts upload --path plankton-${TRAVIS_BUILD_NUMBER}.zip --target-path builds
